<a href="https://colab.research.google.com/github/joelalonsov/hyperblog/blob/main/Actividad3BDManipulacion_A01796712.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**MAESTRÍA EN INTELIGENCIA ARTIFICIAL APLICADA**

**Curso: TC4029 - Ciencia y analítica de datos**

Tecnológico de Monterrey

Prof Grettel Barceló Alonso

**Semana 3**
Bases, almacenes y manipulación de datos

---

*   **NOMBRE**: Joel Alonso Vázquez
*   **MATRÍCULA**: A01796712

---

En esta actividad usarás la base de datos relacional `classicmodels` (MySQL), compuesta por las siguientes tablas:

*   `Customers`: almacena los datos de los clientes.
*   `Products`: almacena una lista de modelos de coches a escala.
*   `ProductLines`: almacena una lista de categorías de líneas de productos.
*   `Orders`: almacena los pedidos de venta realizados por los clientes.
*   `OrderDetails`: almacena elementos de línea de pedidos de ventas para cada pedido de ventas.
*   `Payments`: almacena los pagos realizados por los clientes en función de sus cuentas.
*   `Employees`: almacena toda la información de los empleados, así como la estructura de la organización, como quién informa a quién.
*   `Offices`: almacena los datos de la oficina de ventas.

Revisa con detalle su esquema para que comprendas cómo se relacionan las tablas anteriores.

Recuerda que:


*   Una **clave primaria** es un atributo (o conjunto) que identifica unívocamente a cada registro en la tabla.
*   Una **clave foránea** (externa o ajena) es un atributos (o conjunto) en una tabla que es una clave primaria en otra (o posiblemente la misma) tabla.
*   Las **relaciones** son las líneas que conectan una tabla con otra y el extremo determina la cardinalidad. Las relaciones con línea continua (identificadora) representan una transformación donde la clave primaria de una tabla pasa a ser foránea y primaria (al mismo tiempo) de otra. Las relaciones con línea discontinua (no identificadora) representan una transformación donde la clave primaria de una tabla pasa a ser sólo foránea en otra.

# **Parte 1**. SQLAlchemy y SQL básico

In [1]:
pip install pymysql

Collecting pymysql
  Downloading PyMySQL-1.1.1-py3-none-any.whl.metadata (4.4 kB)
Downloading PyMySQL-1.1.1-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.0/45.0 kB 1.6 MB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.1.1

In [2]:
import sqlalchemy as sqla
import pymysql
import pandas as pd

1.	Crea el motor `sqlalchemy`, con el método `create_engine()` y una conexión con `connect()` como se muestra a continuación:

In [3]:
# Crear el motor (dialecto://usuarioBD:clave@ipHostDBMS:puerto/esquema
db = sqla.create_engine('mysql+pymysql://mnaTC4029User:mnaTC4029Pass!@20.106.217.214:3306/classicmodels', pool_recycle=3600)

# Crea una conexión para luego invocar declaraciones SQL
conn = db.connect()

Escribe las consultas en SQL para obtener:

2.	La información de las líneas de productos.

In [14]:
# Intenta realizar un rollback para limpiar cualquier transacción pendiente
# Tuve que detener algunas transacciones que duraban demasiado y agregué un limite de resultados.
try:
    conn.rollback()
except Exception as e:
    print(f"Error during rollback: {e}")

query = sqla.text('SELECT * FROM productlines LIMIT 5')
df_productlines = pd.read_sql(query,conn)
df_productlines

,productLine,textDescription,htmlDescription,image
0,Classic Cars,Attention car enthusiasts: Make your wildest c...,None,None
1,Motorcycles,Our motorcycles are state of the art replicas ...,None,None
2,Planes,"Unique, diecast airplane and helicopter replic...",None,None
3,Ships,The perfect holiday or anniversary gift for ex...,None,None
4,Trains,Model trains are a rewarding hobby for enthusi...,None,None

**rollback:**
En la primera ejecución no agregué un límite y la consulta estaba tardando demasiado tiempo, al detener la ejecución y volver a inicarla con "LIMIT", marcó un error al no ejecutar "rollback". Por eso fue necesario agregar este código pues quedó un proceso activo que era necesario detener.

3.	La información de los empleados ordenados por nombre (`firstName`).

In [15]:
query = sqla.text('SELECT * FROM employees ORDER BY firstName LIMIT 5')
df_employees = pd.read_sql(query,conn)
df_employees

,employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle
0,1611,Fixter,Andy,x101,afixter@classicmodelcars.com,6,1088.0,Sales Rep
1,1143,Bow,Anthony,x5428,abow@classicmodelcars.com,1,1056.0,Sales Manager (NA)
2,1504,Jones,Barry,x102,bjones@classicmodelcars.com,7,1102.0,Sales Rep
3,1002,Murphy,Diane,x5800,dmurphy@classicmodelcars.com,1,NaN,President
4,1286,Tseng,Foon Yue,x2248,ftseng@classicmodelcars.com,3,1143.0,Sales Rep

4.	Los países donde hay oficinas (sin duplicar).

In [16]:
query = sqla.text('SELECT DISTINCT(country) FROM offices')
df_offices = pd.read_sql(query,conn)
df_offices

     country
0        USA
1     France
2      Japan
3  Australia
4         UK

5.	El nombre y teléfono de los clientes de la ciudad de Nueva York (*NYC*).

In [38]:
query = sqla.text('SELECT customerName, phone FROM customers WHERE city = \'NYC\'')
df_customers = pd.read_sql(query,conn)
df_customers

           customerName       phone
0     Land of Toys Inc.  2125557818
1    Muscle Machine Inc  2125557413
2       Vitachrome Inc.  2125551500
3  Classic Legends Inc.  2125558493
4       Microscale Inc.  2125551957

6.	El código y nombre de los productos del vendedor *Gearbox Collectibles* que tengan menos de 1000 unidades en stock.

In [21]:
query = sqla.text('SELECT productCode, productName FROM products WHERE productVendor = \'Gearbox Collectibles\' AND quantityInStock < 1000')
df_Gearbox = pd.read_sql(query,conn)
df_Gearbox

  productCode             productName
0    S18_2581          P-51-D Mustang
1    S18_2795  1928 Mercedes-Benz SSK

7.	Los tres productos más caros, desde el punto de visto de los comercializadores (`buyPrice`).

In [26]:
query = sqla.text('SELECT * FROM products ORDER BY buyPrice DESC LIMIT 3')
df_buyPrice = pd.read_sql(query,conn)
df_buyPrice

,productCode,productName,productLine,productScale,productVendor,productDescription,quantityInStock,buyPrice,MSRP
0,S10_4962,1962 LanciaA Delta 16V,Classic Cars,1:10,Second Gear Diecast,Features include: Turnable front wheels; steer...,6791,103.42,147.74
1,S18_2238,1998 Chrysler Plymouth Prowler,Classic Cars,1:18,Gearbox Collectibles,Turnable front wheels; steering function; deta...,4724,101.51,163.73
2,S10_1949,1952 Alpine Renault 1300,Classic Cars,1:10,Classic Metal Creations,Turnable front wheels; steering function; deta...,7305,98.58,214.30

8.	La cantidad de productos por línea de producto (no las existencias en inventario)

In [31]:
try:
    conn.rollback()
except Exception as e:
    print(f"Error during rollback: {e}")

query = sqla.text('SELECT productline, count(*) FROM products GROUP BY productLine')
df_productLine = pd.read_sql(query,conn)
df_productLine

        productline  count(*)
0      Classic Cars        38
1       Motorcycles        13
2            Planes        12
3             Ships         9
4            Trains         3
5  Trucks and Buses        11
6      Vintage Cars        24

9.	La cantidad de empleados por país (tomando en cuenta la ubicación de la oficina).

In [52]:
try:
    conn.rollback()
except Exception as e:
    print(f"Error during rollback: {e}")

#query = sqla.text('SELECT o.country, COUNT(e.employeeNumber) AS Total_Empleados FROM employees e JOIN offices o ON e.officeCode = o.officeCode GROUP BY o.country')
query = sqla.text('SELECT o.country, COUNT(e.employeeNumber) AS Total_Empleados FROM employees e JOIN offices o USING(officeCode) GROUP BY o.country')
df_buyPrice = pd.read_sql(query,conn)
df_buyPrice

     country  Total_Empleados
0  Australia                4
1     France                5
2      Japan                2
3         UK                2
4        USA               10

10.	El promedio de los pagos de cada uno de los clientes de España (sin incluir aquellos que no poseen ningún pago).

In [54]:
try:
    conn.rollback()
except Exception as e:
    print(f"Error during rollback: {e}")

#query = sqla.text('SELECT c.customerName, AVG(p.amount) AS Promedio_Pagos FROM payments p LEFT JOIN customers c ON c.customerNumber = p.customerNumber WHERE c.country = \'Spain\' GROUP BY c.customerName')
query = sqla.text('SELECT c.customerName, AVG(p.amount) AS Promedio_Pagos FROM payments p LEFT JOIN customers c USING(customerNumber) WHERE c.country = \'Spain\' GROUP BY c.customerName')
df_AVG = pd.read_sql(query,conn)
df_AVG

                 customerName  Promedio_Pagos
0                 CAF Imports    23375.570000
1  Corrida Auto Replicas, Ltd    37480.030000
2          Enaco Distributors    22840.156667
3      Euro+ Shopping Channel    55056.844615
4  Iberia Gift Imports, Corp.    25493.925000

# **Parte 2**. Manipulación de datos con Pandas

11.	Carga las tablas empleadas en dataframes con el mismo nombre y resuelve las consultas anteriores con las funciones de Pandas (NO con SQL). Cuida no sobreescribir los dataframes originales al resolver las consultas. Debes obtener los mismos resultados que con SQL.

In [58]:
try:
    conn.rollback()
except Exception as e:
    print(f"Error during rollback: {e}")

df_productlines = pd.read_sql('SELECT * FROM productlines', conn)
#df_productlines
df_products = pd.read_sql('SELECT * FROM products', conn)
#df_products
df_orderdetails = pd.read_sql('SELECT * FROM orderdetails', conn)
#df_orderdetails
df_employees = pd.read_sql('SELECT * FROM employees', conn)
#df_employees
df_customers = pd.read_sql('SELECT * FROM customers', conn)
#df_customers
df_orders = pd.read_sql('SELECT * FROM orders', conn)
#df_orders
df_offices = pd.read_sql('SELECT * FROM offices', conn)
#df_offices
df_payments = pd.read_sql('SELECT * FROM payments', conn)
#display(df_payments, df_products)

In [59]:
# 2. La información de las líneas de productos.
# SELECT * FROM productlines
df_productlines

,productLine,textDescription,htmlDescription,image
0,Classic Cars,Attention car enthusiasts: Make your wildest c...,None,None
1,Motorcycles,Our motorcycles are state of the art replicas ...,None,None
2,Planes,"Unique, diecast airplane and helicopter replic...",None,None
3,Ships,The perfect holiday or anniversary gift for ex...,None,None
4,Trains,Model trains are a rewarding hobby for enthusi...,None,None
5,Trucks and Buses,The Truck and Bus models are realistic replica...,None,None
6,Vintage Cars,Our Vintage Car models realistically portray a...,None,None

In [80]:
# 3. La información de los empleados ordenados por nombre (firstName).
# SELECT * FROM employees ORDER BY firstName
df_employees.sort_values('firstName')

,employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle
17,1611,Fixter,Andy,x101,afixter@classicmodelcars.com,6,1088.0,Sales Rep
5,1143,Bow,Anthony,x5428,abow@classicmodelcars.com,1,1056.0,Sales Manager (NA)
16,1504,Jones,Barry,x102,bjones@classicmodelcars.com,7,1102.0,Sales Rep
0,1002,Murphy,Diane,x5800,dmurphy@classicmodelcars.com,1,NaN,President
10,1286,Tseng,Foon Yue,x2248,ftseng@classicmodelcars.com,3,1143.0,Sales Rep
11,1323,Vanauf,George,x4102,gvanauf@classicmodelcars.com,3,1143.0,Sales Rep
13,1370,Hernandez,Gerard,x2028,ghernande@classicmodelcars.com,4,1102.0,Sales Rep
4,1102,Bondur,Gerard,x5408,gbondur@classicmodelcars.com,4,1056.0,Sale Manager (EMEA)
2,1076,Firrelli,Jeff,x9273,jfirrelli@classicmodelcars.com,1,1002.0,VP Marketing
8,1188,Firrelli,Julie,x2173,jfirrelli@classicmodelcars.com,2,1143.0,Sales Rep
15,1501,Bott,Larry,x2311,lbott@classicmodelcars.com,7,1102.0,Sales Rep
6,1165,Jennings,Leslie,x3291,ljennings@classicmodelcars.com,1,1143.0,Sales Rep
7,1166,Thompson,Leslie,x4065,lthompson@classicmodelcars.com,1,1143.0,Sales Rep
12,1337,Bondur,Loui,x6493,lbondur@classicmodelcars.com,4,1102.0,Sales Rep
20,1621,Nishi,Mami,x101,mnishi@classicmodelcars.com,5,1056.0,Sales Rep
22,1702,Gerard,Martin,x2312,mgerard@classicmodelcars.com,4,1102.0,Sales Rep
1,1056,Patterson,Mary,x4611,mpatterso@classicmodelcars.com,1,1002.0,VP Sales
14,1401,Castillo,Pamela,x2759,pcastillo@classicmodelcars.com,4,1102.0,Sales Rep
18,1612,Marsh,Peter,x102,pmarsh@classicmodelcars.com,6,1088.0,Sales Rep
9,1216,Patterson,Steve,x4334,spatterson@classicmodelcars.com,2,1143.0,Sales Rep
19,1619,King,Tom,x103,tking@classicmodelcars.com,6,1088.0,Sales Rep
3,1088,Patterson,William,x4871,wpatterson@classicmodelcars.com,6,1056.0,Sales Manager (APAC)
21,1625,Kato,Yoshimi,x102,ykato@classicmodelcars.com,5,1621.0,Sales Rep

In [79]:
# 4. Los países donde hay oficinas (sin duplicar).
# SELECT DISTINCT(country) FROM offices
df_offices['country'].drop_duplicates().to_frame()

     country
0        USA
3     France
4      Japan
5  Australia
6         UK

In [62]:
# 5. El nombre y teléfono de los clientes de la ciudad de Nueva York (NYC).
# SELECT customerName, phone FROM customers WHERE city = \'NYC\'
df_customers[df_customers['city'] == 'NYC'][['customerName', 'phone']]

             customerName       phone
9       Land of Toys Inc.  2125557818
15     Muscle Machine Inc  2125557413
27        Vitachrome Inc.  2125551500
98   Classic Legends Inc.  2125558493
105       Microscale Inc.  2125551957

In [63]:
# 6. El código y nombre de los productos del vendedor Gearbox Collectibles que tengan menos de 1000 unidades en stock.
# SELECT productCode, productName FROM products WHERE productVendor = \'Gearbox Collectibles\' AND quantityInStock < 1000
df_products[(df_products['productVendor'] == 'Gearbox Collectibles') & (df_products['quantityInStock'] < 1000)][['productCode', 'productName']]

   productCode             productName
30    S18_2581          P-51-D Mustang
32    S18_2795  1928 Mercedes-Benz SSK

In [64]:
# 7. Los tres productos más caros, desde el punto de visto de los comercializadores (buyPrice).
# SELECT * FROM products ORDER BY buyPrice DESC LIMIT 3
df_products.sort_values(by='buyPrice', ascending=False).head(3)

,productCode,productName,productLine,productScale,productVendor,productDescription,quantityInStock,buyPrice,MSRP
5,S10_4962,1962 LanciaA Delta 16V,Classic Cars,1:10,Second Gear Diecast,Features include: Turnable front wheels; steer...,6791,103.42,147.74
25,S18_2238,1998 Chrysler Plymouth Prowler,Classic Cars,1:18,Gearbox Collectibles,Turnable front wheels; steering function; deta...,4724,101.51,163.73
1,S10_1949,1952 Alpine Renault 1300,Classic Cars,1:10,Classic Metal Creations,Turnable front wheels; steering function; deta...,7305,98.58,214.30

In [65]:
# 8. La cantidad de productos por línea de producto (no las existencias en inventario)
# SELECT productline, count(*) FROM products GROUP BY productLine
df_products.groupby('productLine').size()

productLine
Classic Cars        38
Motorcycles         13
Planes              12
Ships                9
Trains               3
Trucks and Buses    11
Vintage Cars        24
dtype: int64

In [66]:
# 9. La cantidad de empleados por país (tomando en cuenta la ubicación de la oficina).
# SELECT o.country, COUNT(e.employeeNumber) AS Total_Empleados FROM employees e JOIN offices o ON e.officeCode = o.officeCode GROUP BY o.country
df_employees.merge(df_offices, left_on='officeCode', right_on='officeCode').groupby('country').size()

country
Australia     4
France        5
Japan         2
UK            2
USA          10
dtype: int64

In [75]:
# 10. El promedio de los pagos de cada uno de los clientes de España (sin incluir aquellos que no poseen ningún pago).
# SELECT c.customerName, AVG(p.amount) AS Promedio_Pagos FROM payments p LEFT JOIN customers c ON c.customerNumber = p.customerNumber WHERE c.country = \'Spain\' GROUP BY c.customerName
# SELECT c.customerName, AVG(p.amount) AS Promedio_Pagos FROM payments p LEFT JOIN customers c USING(customerNumber) WHERE c.country = \'Spain\' GROUP BY c.customerName
customers_spain = df_customers[df_customers['country']=='Spain']
df_merged = pd.merge(df_payments, customers_spain, on= 'customerNumber', how='left')
df_merged.groupby('customerName')['amount'].mean().reset_index()

                 customerName        amount
0                 CAF Imports  23375.570000
1  Corrida Auto Replicas, Ltd  37480.030000
2          Enaco Distributors  22840.156667
3      Euro+ Shopping Channel  55056.844615
4  Iberia Gift Imports, Corp.  25493.925000

# **Parte 3**. Cliente de Python Firestore

En esta fase te conectarás a una base de datos no relacional de Firestore desde Python. Para ello utilizarás los módulos `credentials` y `firestore` de la biblioteca `firebase_admin`.

In [81]:
import firebase_admin
from firebase_admin import credentials
from firebase_admin import firestore

El archivo `veterinary.json` almacena la clave privada para autenticar una cuenta y autorizar el acceso a los servicios de Firebase. A través de la función `Certificate()`, se regresa una credencial inicializada, que puedes utilizar para crear una nueva instancia de la aplicación. Después de eso, tu conexión a Firestore utilizará las reglas de seguridad establecidas para la base de datos y el usuario autenticado.

In [82]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [86]:
# Creación de ruta en MyDrive para utilizar el archivo de credenciales JSON:
import os
DIR = "/content/drive/MyDrive/Colab Notebooks/MNA/TC4029 - Ciencia y analítica de datos/Semana 3/Actividad3_BD_Manipulacion"
os.chdir(DIR)

In [87]:
cred = credentials.Certificate('veterinary.json')
firebase_admin.initialize_app(cred)
# Se crea una referencia a firestone:
db = firestore.client()

12.	Investiga cómo leer la colección `PET_OWNER` y mostrar su contenido en un dataframe. Asegúrate de incluir el id en el resultado

In [91]:
# Lectura de los datos de la colección 'PET_OWNER'
# Se crea una referencia a la colección 'PET_OWNER'
pet_owners_ref = db.collection('PET_OWNER')
docs = pet_owners_ref.stream()    #stream permite obtener todos los documentos de la colección.

# Se crea una lista para almacenar los datos
data = []

# Con un ciclo for se recorren los documentos y se agregan los datos a la lista
for doc in docs:
    doc_dict = doc.to_dict()
    doc_dict['id'] = doc.id  # Se agrega el ID del documento al diccionario
    data.append(doc_dict)

# Se convierte la lista de diccionarios en un DataFrame de Pandas
df = pd.DataFrame(data)

# Se muestra el DataFrame
print(df)

  ownerFirstName ownerLastName                        email         phone  \
0            Sam        Taylor                         None  555-454-3465
1          Miles         Trent    miles.trent@somewhere.com          None
2            Liz         Frier      liz.frier@somewhere.com  555-537-6543
3          Jenny      Mayberry                         None  555-454-1243
4         Marsha         Downs  'marcha.downs@somewhere.com  555-537-8765
5            Ken       Roberts                         None  555-454-2354
6          Nigel        Melnik   nigel.melnik@somewhere.com  555-232-5678
7        Richard         James  richard.james@somewhere.com  555-537-7654
8            Jim        Rogers     jim.rogers@somewhere.com  555-232-3456
9           Mary        Keenan    mary.keenan@somewhere.com  555-232-4567

                     id
0  0D6yFSs2eu4nYwf2dnQ0
1  98357ufgjmWUxjnAuzbz
2  AFtZincSZxjC4Mcxf9Pf
3  GYDixDwHjMyihjL8TmsM
4  IpxTuB6FILhwQFcspLws
5  QoXBfS1JdRp6BqgLzaAz
6  eUtZ44lPRbSHXX04EDp7
7  n2GG9rlfGOmE0P4TcU0T
8  pDlJlul8EJXO8FBJvFkN
9  tAlJ74xQ7tT4TUHwZgmH

In [92]:
firebase_admin.delete_app(firebase_admin.get_app())